# Site settings
title: kkaemi의 포트폴리오 사이트입니다
description: A blog about lorem ipsum dolor sit amet
baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "kkaemi.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Kkaemi
user_description: 현재 백엔드 개발자 취업을 희망하고 있는 취업준비생 지성현입니다.
user_title: I wanna be a backend developer
email: kitys2k3@naver.com
instagram_username: kkaemi
github_username:  Kkaemi

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
